id: 1e0862064425475895900563349ac16b
initial_creation_type: ebook
created_at: 27/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmp5gkl1uow.jpg
  credit: tmpaof6ypcj.jpg
